# Generated by Django 4.1.10 on 2024-02-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0002_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Approve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camp_id", models.BigIntegerField()),
                ("approved", models.BooleanField(default=False)),
                ("rejected", models.BooleanField(default=False)),
            ],
        ),
    ]
