# Generated by Django 4.1.10 on 2024-02-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0004_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(upload_to="images/%Y/%m/%d/"),
        ),
    ]
