# Generated by Django 4.1.10 on 2024-02-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic", "0005_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="users/%Y/%m/%d/"),
        ),
    ]
